# Generated by Django 3.2.4 on 2021-08-07 00:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('Tags', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=100, size=5)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
