# Generated by Django 3.2.4 on 2021-08-07 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderite', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='coderite/assets', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
