# Generated by Django 3.2.4 on 2021-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderite', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tags',
        ),
        migrations.AddField(
            model_name='post',
            name='Tags1',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='Tags2',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='Tags3',
            field=models.CharField(default='blank', max_length=50),
        ),
    ]
