# Generated by Django 3.2.4 on 2021-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderite', '0004_auto_20210807_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tags1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tags2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tags3',
        ),
        migrations.AddField(
            model_name='post',
            name='field_tag',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='lang_tag',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='level_tag',
            field=models.CharField(default='blank', max_length=50),
        ),
    ]
